# Generated by Django 4.2.10 on 2024-03-16 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_alter_instrument_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='instrument',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Rented', 'Rented'), ('Returned', 'Returned'), ('Available', 'Available'), (' NOT Available', 'NOT Available')], max_length=255, null=True),
        ),
    ]
