# Generated by Django 4.2.10 on 2024-03-30 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_rentinstruments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentinstruments',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Declined', 'Declined'), ('Cancelled', 'Cancelled'), ('Pending', 'Pending')], default='pending', max_length=255),
        ),
    ]
