# Generated by Django 4.2.10 on 2024-04-06 03:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('frontend', '0007_alter_rentinstruments_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentinstruments',
            name='instrument',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='frontend.instrument'),
        ),
        migrations.AlterField(
            model_name='rentinstruments',
            name='renter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rentinstruments',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Declined', 'Declined'), ('Cancelled', 'Cancelled'), ('Pending', 'Pending')], default='Pending', max_length=255, null=True),
        ),
    ]
